import { StyleSheet } from "react-native";
import { CARD_W, CARD_H, CARD_R } from "./constants";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#060a12",
    gap: 28,
  },
  shadowWrap: {
    borderRadius: CARD_R,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 16 },
    shadowRadius: 44,
    shadowOpacity: 0.58,
    elevation: 20,
  },
  cardContainer: { width: CARD_W, height: CARD_H },
  cardFace: {
    width: CARD_W,
    height: CARD_H,
    borderRadius: CARD_R,
    overflow: "hidden",
    backgroundColor: "#0d1628",
    borderWidth: 0.5,
    borderColor: "rgba(100,160,255,0.18)",
  },
  cardUI: {
    ...StyleSheet.absoluteFillObject,
    paddingTop: 18,
    paddingBottom: 20,
    paddingHorizontal: 22,
    justifyContent: "space-between",
  },
  cardTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
  },
  bankName: {
    color: "rgba(215,235,255,0.88)",
    fontSize: 20,
    fontWeight: "500",
  },
  topRight: { alignItems: "flex-end", gap: 4 },
  debit: { color: "rgba(215,235,255,0.70)", fontSize: 16, fontWeight: "500" },
  cardNumberText: {
    color: "rgba(195,230,255,0.9)",
    fontSize: 22,
    lineHeight: 34,
    letterSpacing: 1.2,
    textShadowColor: "rgba(76,165,245,0.78)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 7,
  },
  cardNumberFont: {
    fontFamily: "ShareTechMono",
  },
  cardBot: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  expiry: {
    color: "rgba(255,255,255,0.30)",
    fontSize: 11,
    fontFamily: "Courier",
    marginTop: 4,
  },
  mastercard: { alignItems: "center", gap: 2 },
  network: { flexDirection: "row", alignItems: "center" },
  netCircle: { width: 30, height: 30, borderRadius: 15, opacity: 0.88 },
  mastercardText: {
    color: "rgba(215,235,255,0.60)",
    fontSize: 11,
    fontWeight: "500",
    letterSpacing: 0.3,
  },
  magStripe: {
    position: "absolute",
    top: 36,
    left: 0,
    right: 0,
    height: 42,
    backgroundColor: "rgba(0,0,0,0.88)",
  },
  signatureBlock: {
    position: "absolute",
    top: 94,
    left: 22,
    right: 22,
    gap: 5,
  },
  signatureLabel: {
    color: "rgba(215,235,255,0.46)",
    fontSize: 7,
    fontWeight: "700",
    letterSpacing: 1.2,
  },
  signatureRow: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 8,
  },
  signatureStrip: {
    flex: 1,
    height: 42,
    overflow: "hidden",
    borderRadius: 3,
    backgroundColor: "rgba(244,248,252,0.90)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(255,255,255,0.70)",
  },
  signatureLine: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: "rgba(30,65,105,0.09)",
  },
  signatureHint: {
    position: "absolute",
    left: 10,
    bottom: 6,
    color: "rgba(24,38,54,0.30)",
    fontSize: 7,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  cvvPanel: {
    width: 58,
    height: 42,
    borderRadius: 3,
    backgroundColor: "rgba(255,255,255,0.92)",
    alignItems: "center",
    justifyContent: "center",
  },
  cvvLabel: {
    color: "rgba(18,30,44,0.42)",
    fontSize: 7,
    fontWeight: "800",
    fontFamily: "Courier",
    letterSpacing: 0.8,
  },
  cvvNum: {
    color: "#111",
    fontSize: 13,
    fontFamily: "Courier",
    letterSpacing: 1.5,
  },
  backBrand: {
    position: "absolute",
    bottom: 30,
    left: 22,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  backLogoMark: {
    width: 24,
    height: 24,
    borderRadius: 7,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(215,235,255,0.13)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(215,235,255,0.25)",
  },
  backLogoText: {
    color: "rgba(215,235,255,0.72)",
    fontSize: 15,
    fontWeight: "800",
  },
  backBank: {
    color: "rgba(255,255,255,0.22)",
    fontSize: 12,
    fontWeight: "700",
  },
  backFinePrint: {
    position: "absolute",
    left: 22,
    right: 116,
    bottom: 13,
    color: "rgba(215,235,255,0.24)",
    fontSize: 6.5,
    lineHeight: 8,
    letterSpacing: 0.2,
  },
  backNet: {
    position: "absolute",
    bottom: 18,
    right: 22,
    color: "rgba(255,255,255,0.26)",
    fontSize: 10,
    fontStyle: "italic",
  },
  hint: {
    color: "rgba(100,140,220,0.38)",
    fontSize: 11,
    fontFamily: "Courier",
    letterSpacing: 0.5,
  },
});
